[package]
name = "example-model"
version = "0.1.0"
edition = "2021"

[dependencies]
ankurah-core = { path = "../../core", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2"