[package]
name    = "example-model"
version = "0.1.0"
edition = "2021"

[features]
default = ["wasm"]
wasm    = ["dep:wasm-bindgen", "ankurah-core/wasm"]

[dependencies]
ankurah-core = { path = "../../core", features = ["derive"] }
serde        = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2", optional = true }
