[package]
name    = "example-model"
version = "0.2.2"
edition = "2021"
publish = false

[features]
default = ["wasm"]
wasm    = ["dep:wasm-bindgen", "ankurah/wasm"]

[dependencies]
ankurah      = { path = "../../ankurah", features = ["derive"], version = "^0.2.2" }
serde        = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2", optional = true }
