[package]
name        = "ankurah-core"
description = "Core state management functionality for Ankurah"
version     = "0.1.3"
edition     = "2021"
license     = "MIT OR Apache-2.0"

[features]
default = []

[dependencies]
# Internal dependencies
ankurah-derive = { path = "../derive", optional = true, version = "^0.1.2" }
ankql          = { path = "../ankql", version = "^0.1.2" }
ankurah-proto  = { path = "../proto", version = "^0.1.1" }

rand            = "0.8"
dashmap         = "6.1"
anyhow          = "1.0"
thiserror       = "2"
chrono          = { version = "0.4", default-features = false }
futures-signals = "0.3"
serde           = "1.0"
ulid            = { version = "1.1", features = ["serde", "uuid"] }
uuid            = "1.1"
tracing         = "0.1.40"
bincode         = "1.3.3"
append-only-vec = "0.1"
async-trait     = "0.1"
yrs             = "0.21.2"
tokio           = { version = "1.40", default-features = false, features = ["sync", "rt", "time", "macros"] }
futures         = "0.3"
tokio-postgres  = { version = "0.7", features = ["with-uuid-1"], optional = true }
bb8             = { version = "0.9", optional = true }
bb8-postgres    = { version = "0.9", optional = true }
futures-util    = "0.3"
dirs            = { version = "6.0", optional = true }
sled            = { version = "0.34", optional = true }

[dev-dependencies]
