[package]
name          = "ankurah-storage-sled"
version       = "0.6.3"
edition       = "2021"
description   = "Ankurah storage engine using Sled"
license       = "MIT OR Apache-2.0"
documentation = "https://docs.rs/ankurah-storage-sled"
homepage      = "https://github.com/ankurah/ankurah"
repository    = "https://github.com/ankurah/ankurah"

[dependencies]
ankurah-proto          = { path = "../../proto", version = "^0.6.3" }
ankurah-core           = { path = "../../core", version = "^0.6.3" }
ankql                  = { path = "../../ankql", version = "^0.6.3" }
ankurah-storage-common = { path = "../common", version = "^0.6.3" }
anyhow                 = "1.0"
async-trait            = "0.1"
sled                   = "0.34"
tokio                  = "1"
bincode                = "1.3"
serde                  = { version = "1.0", features = ["derive"] }
blake3                 = "1"
chrono                 = { version = "0.4", default-features = false, features = ["clock"] }
dirs                   = "6.0"
ulid                   = "1.1"
tracing                = "0.1"
thiserror              = "2.0"

[dev-dependencies]
ankurah            = { path = "../../ankurah", version = "^0.6.3", features = ["derive"] }
ctor               = "0.5"
tracing-subscriber = "0.3"
