[package]
name    = "ankurah-storage-sled"
version = "0.1.0"
edition = "2024"

[dependencies]
ankurah-proto = { path = "../../proto" }
ankurah-core  = { path = "../../core" }
ankql         = { path = "../../ankql" }
anyhow        = "1.0"
async-trait   = "0.1"
sled          = "0.34"
tokio         = "1"
bincode       = "1.3"
dirs          = "6.0"
ulid          = "1.1"
