name: Format Check

on:
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install rustfmt
        run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt

      - name: Install Taplo
        run: cargo install taplo-cli

      - name: Check Rust formatting
        run: cargo fmt --all -- --check

      - name: Check TOML formatting
        run: taplo fmt --check

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Prettier
        run: npm install -g prettier

      - name: Check TypeScript formatting
        run: prettier --check "examples/react-app/src/**/*.{ts,tsx}"
