name: Publish Crates

on:
  push:
    branches: [main]
    paths: ["**/Cargo.toml"]

permissions:
  contents: write # Need to create and push tags

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run publish script
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: ./.release/publish.sh

      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::Publishing failed. Check the logs above for details."
