name: Auto Version Bump

on:
  pull_request:
    paths:
      - "RELEASES"
    types: [opened, synchronize]

permissions:
  contents: write # Need to commit version bumps and push to PR branch
  pull-requests: write # Need to comment on PRs
  issues: write # Required for creating PR comments (comments are treated as issues)

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          # Fetch more history for safety checks
          fetch-depth: 10

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make bump script executable
        run: chmod +x .release/bump-version.sh

      - name: Run version bump
        id: bump
        run: |
          # Record the current commit hash before running the script
          COMMIT_BEFORE=$(git rev-parse HEAD)

          echo "Running version bump script..."
          ./.release/bump-version.sh

          # Check if a new commit was created
          COMMIT_AFTER=$(git rev-parse HEAD)
          if [ "$COMMIT_BEFORE" = "$COMMIT_AFTER" ]; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
            echo "No version changes were needed"
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
            echo "Version bump changes committed"
          fi

      - name: Push version bump changes
        if: steps.bump.outputs.no_changes == 'false'
        run: |
          echo "Pushing version bump changes..."
          git push origin ${{ github.event.pull_request.head.ref }}

      - name: Comment on PR
        if: steps.bump.outputs.no_changes == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 **Auto Version Bump**\n\nI\'ve automatically updated the crate versions to match the latest entry in the RELEASES file. The changes have been committed to this PR.'
            })

      - name: Skip notification
        if: steps.bump.outputs.no_changes == 'true'
        run: |
          echo "✓ Versions are already up to date - no action needed"
